Repository AndiDittrich/Node.CLI-Progress, pull requests merged in 2019-10, with the labels that each got.

#49 Bugfix: Fixing issues with falsy values in format
  lib/formatter.js
  package-lock.json
  package.json
  test/.eslintrc.json
  test/lib/formatter.test.js
Labels: bug, enhancement, feature-request

#50 Update to use consistent naming in README
  README.md
Labels: enhancement, validated

#51 Fix documentation for the `stream` option
  README.md
Labels: enhancement
